eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: cloud-eureka-client
logging:
  file: "logs/cloud-eureka-client.log"
management:
  security:
    enabled: false
