spring:
  application:
    name: config-server
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/MichaelWong093/SpringCloudStudy10
#          search-paths: cloud-parent/cloud-config-server/src/main/resources/shared/
#          username:
#          password:
#      label: master
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared

server:
  port: 8769

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
