spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://{ip}:{port}/spring-security?userUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9090
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true